-- King’s Cafe manager schema. Review and run in Supabase SQL editor only after
-- creating the project and confirming the authenticated staff roles.

create extension if not exists "pgcrypto";

create table if not exists public.cafe_settings (
  id uuid primary key default gen_random_uuid(),
  cafe_name text not null,
  branch_name text not null,
  phone text,
  address text,
  logo_url text,
  currency text not null default 'EGP',
  receipt jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  arabic_name text,
  category text not null,
  price numeric(12,2) not null check (price >= 0),
  cost numeric(12,2) check (cost is null or cost >= 0),
  image_url text,
  description text,
  available boolean not null default true,
  available_for_takeaway boolean not null default true,
  visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_customization_groups (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  name text not null,
  required boolean not null default false,
  display_order integer not null default 0,
  unique (product_id, name)
);

create table if not exists public.product_customization_choices (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.product_customization_groups(id) on delete cascade,
  name text not null,
  price numeric(12,2) not null default 0 check (price >= 0),
  display_order integer not null default 0
);

create table if not exists public.cafe_tables (
  id uuid primary key default gen_random_uuid(),
  table_number text not null unique,
  status text not null default 'Available' check (status in ('New','Preparing','Ready','Delivered','Available')),
  session_status text not null default 'Closed' check (session_status in ('Open','Closed')),
  opened_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  table_id uuid references public.cafe_tables(id) on delete set null,
  order_type text not null default 'DineIn' check (order_type in ('DineIn','Takeaway')),
  customer_name text not null,
  guest_label text not null,
  status text not null default 'New' check (status in ('New','Preparing','Ready','Delivered','Cancelled')),
  payment_status text not null default 'Unpaid' check (payment_status in ('Unpaid','Paid','Refunded')),
  payment_method text check (payment_method in ('Cash','Card','Wallet')),
  cashier_id uuid references auth.users(id) on delete set null,
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  cash_received numeric(12,2),
  cash_change numeric(12,2),
  cancellation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  recipient_name text,
  product_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  size text,
  milk text,
  sugar text,
  extras text,
  temperature text,
  note text,
  status text not null default 'New' check (status in ('New','Preparing','Ready','Cancelled')),
  cancellation_reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.order_payments (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  method text not null check (method in ('Cash','Card','Wallet')),
  amount numeric(12,2) not null check (amount >= 0),
  received numeric(12,2),
  change_amount numeric(12,2),
  paid_by uuid references auth.users(id) on delete set null,
  paid_at timestamptz not null default now()
);

alter table public.cafe_settings enable row level security;
alter table public.products enable row level security;
alter table public.product_customization_groups enable row level security;
alter table public.product_customization_choices enable row level security;
alter table public.cafe_tables enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_payments enable row level security;

-- Temporary authenticated-staff policies. Replace with role/branch checks when
-- staff profiles are introduced; never expose these tables anonymously.
do $$
declare table_name text;
begin
  foreach table_name in array array['cafe_settings','products','product_customization_groups','product_customization_choices','cafe_tables','orders','order_items','order_payments'] loop
    execute format('drop policy if exists %I_authenticated_access on public.%I', table_name, table_name);
    execute format('create policy %I_authenticated_access on public.%I for all to authenticated using (true) with check (true)', table_name, table_name);
  end loop;
end $$;

create index if not exists orders_table_status_idx on public.orders(table_id, status, session_status);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists payments_order_idx on public.order_payments(order_id, paid_at desc);
